# Generated by Django 4.2.7 on 2023-11-21 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_club', '0003_bookclub_name_alter_bookclub_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bookclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_club', to='book_club.bookclub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
