# Generated by Django 4.2.7 on 2023-11-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pages_completed',
            field=models.IntegerField(default=0),
        ),
    ]
