# Generated by Django 4.2.5 on 2023-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_pages_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='top_five_books',
            field=models.JSONField(default=list),
        ),
    ]
