# Generated by Django 4.2.5 on 2023-11-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField()),
                ('title', models.CharField()),
                ('pages', models.IntegerField()),
                ('book_cover_id', models.CharField(null=True)),
            ],
        ),
    ]
