# Generated by Django 4.2.7 on 2023-11-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='open_library_id',
            field=models.CharField(default=None),
        ),
    ]
