# Generated by Django 4.2.7 on 2023-11-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='recommended',
        ),
    ]
