# Generated by Django 4.2.7 on 2023-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedbook',
            name='recomended',
        ),
        migrations.AddField(
            model_name='completedbook',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedbook',
            name='user_rating',
            field=models.IntegerField(null=True),
        ),
    ]
